### PR TITLE
[fix]  All product dependencies are correctly discovered

### LINKED ISSUE #456: inter-project dependencies are no longer detected by sls-packaging 3.6.0
## What happened?

An excavator PR bumped to 3.6.0, but it tried to delete some interproject deps:

```diff
 com.palantir.foo:foo (3.42.2, 3.x.x)
 com.palantir.bar:bar (1.0.0, 1.x.x)
 com.palantir.baz:baz (3.18.4, 3.x.x)
-com.palantir.my-project:my-project ($projectVersion, 1.x.x)
-com.palantir.my-project:my-project-work-state ($projectVersion, 1.x.x)
 com.palantir.timelock:timelock-server (0.57.0, 0.x.x)
```

cc @saurabhshukla92 

## What did you want to happen?

Those inter-project deps are necessary and should be kept!!

### PR DESCRIPTION
**Pull request by ferozco**
## Before this PR
Previously, we would not discover product dependencies from transitive project dependencies

## After this PR
We correctly discover all product dependencies produced by project dependencies

closes #456

### CODE REVIEW

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java [hunk 1]
```diff
@@ -313,122 +311,85 @@ private void ensureLockfileIsUpToDate(List<ProductDependency> productDeps) {
...
-    private Stream<ProductDependency> discoverProjectProductDependencies(Configuration config) {
-        return config.getAllDependencies().stream()
-                .flatMap(dependency -> {
-                    if (dependency instanceof ProjectDependency) {
-                        Project dependencyProject = ((ProjectDependency) dependency).getDependencyProject();
+        productDependenciesConfig.get().getIncoming().getArtifacts().getArtifacts().stream()
+                .flatMap(artifact -> {
+                    String artifactName = artifact.getId().getDisplayName();
+                    ComponentIdentifier id = artifact.getId().getComponentIdentifier();
+                    Optional<String> pdeps = Optional.empty();
```
Comment (dansanduleac) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java]: initializer is redundant, and makes variable non-final

**Comment by dansanduleac** [comment]
👍

**Comment by iamdanfox** [comment]
:+1:
