### PR TITLE
Fix missing jars in classpath of generared in jar MANIFEST

### LINKED ISSUE #476: Classpath generated with enableManifestClasspath is missing entries
When using enableManifestClasspath, the main module jar is not added to the generated classpath.

As a result, the main class cannot be resolved and the application fails to start.

The problem can also be observed by comparing the classpath generated with and without the enableManifestClasspath flag.

### PR DESCRIPTION
**Pull request by joncelay**
fixes #476 

Classpath in jar MANIFEST  now contains the project jars and is consistent with the classpath generated in launcher script.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/sls-packaging](https://github.com/palantir/sls-packaging), @joncelay! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java [hunk 1]
```diff
@@ -85,8 +86,14 @@ public void apply(Project project) {
                     task.setAppendix("manifest-classpath");
 
                     task.doFirst(t -> {
-                        String classPath = project.getConfigurations().getByName("runtimeClasspath")
-                                .getFiles()
+
+                        FileCollection runtimeClasspath = project.getConfigurations().getByName("runtimeClasspath");
+
+                        TaskProvider<Jar> jarTask = project.getTasks().withType(Jar.class)
+                                .named(JavaPlugin.JAR_TASK_NAME);
```
Comment (dansanduleac) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java]: could we inline this into the below? also can do `getByName` rather than `named` if you're just gonna `.get()` it right afterwards

**Review by dansanduleac — APPROVED** [review]
