### PR TITLE
Fix inter project product dependencies

### LINKED ISSUE #527: productDependencies configuration might be broken with $project versions
## What happened?

Using sls-packaging 3.7.5 and upgrading gradle-docker 0.21.0 -> 0.22.1, an internal project started failing with the following:

```
* What went wrong:
Execution failed for task ':lang-java-template-asset:resolveConfigurations'.
> Could not resolve all files for configuration ':lang-java-template-asset:docker'.
   > Could not find com.palantir.t.java:lang-java-asset-bundle-mega:1.97.0-18-gbdf74d8.
     Searched in the following locations:
```

Interestingly, this was the only project that had a `$projectVersion` inter-project dependency.

```
# Run ./gradlew --write-locks to regenerate this file
com.palantir.s.m:s-module-m (3.40.0, 3.x.x)
com.palantir.t.java:lang-java-asset-bundle-mega ($projectVersion, 1.x.x)
com.palantir.t.java:lang-java-s-module-asset (1.96.0, 1.x.x)
```

The `generateDockerCompose` task also failed, with the same error.

Workaround was to exclude this specific module from the `docker` configuration, as the templating functionality was never actually used!

```gradle
configurations.productDependencies {
    exclude module: 'lang-java-asset-bundle-mega'
}
```

## What did you want to happen?

`$projectVersion` should not fail to resolve, but be propagated nicely into the resultant docker-compose.yml.

### PR DESCRIPTION
**Pull request by dansanduleac**
## Before this PR

Inter-project pdeps could fail to resolve in some circumstances, particularly when the `serviceGroup` and `serviceName` of the project didn't match the `productGroup` and `productName` of the actual dependency.

## After this PR
==COMMIT_MSG==
Inter-project product dependencies are now correctly wired up to point to the projects themselves, and additionally to recursively collect those transitive projects' product dependencies.

Fixes #527
==COMMIT_MSG==

### CODE REVIEW

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+
+package com.palantir.gradle.dist;
+
+import java.lang.reflect.Proxy;
+import org.gradle.api.DomainObjectCollection;
+import org.gradle.api.GradleException;
+import org.gradle.api.provider.ListProperty;
+
+@SuppressWarnings("UnstableApiUsage")
+final class GradleWorkarounds {
```
Comment (ferozco) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java:25]: I'd rather just bump our min dep than keep this around

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java [hunk 2]
```diff
@@ -45,13 +51,13 @@ public void apply(Project project) {
...
-                    conf.getDependencies().addAll(createAllProductDependencies(project, productDependencies)));
-
-            if (!allProductDependencies.isPresent()) {
-                log.info("Lock file not present, not populating product dependencies configuration: {}", conf);
-            }
+            // Lazily wire up product dependencies
+            Provider<List<ProductDependency>> allProductDependencies =
+                    project.provider(() -> getAllProductDependencies(project).orElseGet(ImmutableList::of));
+            ListProperty<Dependency> dependencies = project.getObjects().listProperty(Dependency.class);
+            dependencies.set(allProductDependencies.map(pdeps ->
```
Comment (ferozco) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:58]:
```suggestion
            ListProperty<Dependency> dependencies = project.getObjects().listProperty(Dependency.class)
            .value(allProductDependencies.map(pdeps ->
```

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java [hunk 3]
```diff
@@ -103,13 +107,43 @@ private static String getMinimumProductVersion(Project project, String group, St
...
+                            .create(ImmutableMap.of(
+                                    "group", dependency.getProductGroup(),
+                                    "name", dependency.getProductName(),
+                                    "version", dependency.getMinimumVersion()));
+                })
                 .collect(Collectors.toList());
     }
+
+    public static Map<ProductId, Project> getInRepoProductIds(Project rootProject) {
+        Preconditions.checkArgument(
```
Comment (ferozco) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:132]: Instead of failing can we just grab the root project?

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java [hunk 4]
```diff
@@ -103,13 +107,43 @@ private static String getMinimumProductVersion(Project project, String group, St
...
+            Project project, List<ProductDependency> dependencies, Map<ProductId, Project> inRepoProductIds) {
         return dependencies.stream()
-                .map(dependency -> project.getDependencies()
-                        .create(ImmutableMap.of(
-                                "group", dependency.getProductGroup(),
-                                "name", dependency.getProductName(),
-                                "version", dependency.getMinimumVersion())))
+                .map(dependency -> {
+                    ProductId productId = new ProductId(dependency.getProductGroup(), dependency.getProductName());
+                    if (inRepoProductIds.containsKey(productId)) {
```
Comment (ferozco) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:115]: Optional.ofNullable(inRepoProductIds.get(productId)
   .map(...)
   .orElseGet(...)

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java (hunk 2 above)
Comment (dansanduleac) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:58]: yeah, requires gradle 6 so I didn't do it

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java (hunk 3 above)
Comment (dansanduleac) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:132]: I wanted to fail in order to make it clear from the parameter what is acceptable and what is not

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java (hunk 1 above)
Comment (dansanduleac) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java:25]: Could do, but not everyone's off gradle 5 so it might cause unnecessary friction. This is a bit gross but copied wholesale from GCV and we know it works.

Comment (ferozco) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java:25]: given that we're approaching 6.4 I think its ok the raise the dep but sure

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java (hunk 2 above)
Comment (ferozco) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java:58]: :(

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java [hunk 5]
```diff
@@ -169,6 +169,10 @@ public CreateManifestTask() {
         return ignoredProductIds;
     }
 
+    final SetProperty<ProductId> getInRepoProductIds() {
```
Comment (ferozco) [inline gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java:173]: This should also be annotated as an input

File: gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java (hunk 1 above)
Comment (chrismale) [reply gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/GradleWorkarounds.java:25]: It'd be great to tackle the dep lift in a separate PR, just to help us laggers out a little.

**Comment by ferozco** [comment]
👍

**Comment by ferozco** [comment]
🤖 🍿
